# Generated by Django 4.2.20 on 2025-05-27 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_credit_model_for_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(blank=True, help_text='Users for whom this flag is enabled. Leave empty for global.', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
