# Generated by Django 4.2.20 on 2025-06-02 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_feature_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for being banned', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bare_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
