# Generated by Django 4.2.20 on 2025-06-30 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_create_bareduser_modal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to=settings.AUTH_USER_MODEL),
        ),
    ]
