version: '3.8'

services:
  nginx:
    build: ./nginx
    image: ${REGISTRY_URL:-localhost}/imageassistant_nginx:${TAG:-latest}
    ports:
      - 443:443
      - 80:80
    depends_on:
      - django
    networks:
      - imageassistant-network
    volumes:
      # change to your static path
      - static:/home/ubuntu/app/imageassistant/imageassistant/static/
      - /etc/letsencrypt:/etc/letsencrypt
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  redis-imageassistant:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - imageassistant-network
  django:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ${REGISTRY_URL:-localhost}/imageassistant_django:${TAG:-latest}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      # set to your production settings file
      - DJANGO_SETTINGS_MODULE=config.production_settings
    command: >
      sh -c "
              python manage.py migrate && 
              python manage.py collectstatic --noinput &&
              gunicorn config.wsgi:application --bind 0.0.0.0:8084"
    volumes:
      - static:/usr/src/imageassistant/imageassistant/config/static/
    ports:
      - 8084:8084
    networks:
      - imageassistant-network
    depends_on:
      - redis-imageassistant
  celery-imageassistant:
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    image: ${REGISTRY_URL:-localhost}/imageassistant_celery:${TAG:-latest}
    environment:
      # set to your production settings file
      - DJANGO_SETTINGS_MODULE=config.production_settings
    command: >
      sh -c "celery -A config worker --loglevel=info --max-tasks-per-child=1 --concurrency=4"
    depends_on:
      - redis-imageassistant
    networks:
      - imageassistant-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
networks:
  imageassistant-network:
    driver: overlay
    attachable: true

volumes:
  static:
  redis-data:


