version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 443:443
      - 80:80
    depends_on:
      - django
    networks:
      - imageassistant-network
    volumes:
      # change to your static path
      - static:/home/ubuntu/app/imageassistant/imageassistant/static/
      - /etc/letsencrypt:/etc/letsencrypt
  redis-imageassistant:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - imageassistant-network
  django:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      # set to your production settings file
      - DJANGO_SETTINGS_MODULE=config.production_settings
    command: >
      sh -c "
              python manage.py migrate && 
              python manage.py collectstatic --noinput &&
              gunicorn config.wsgi:application --bind 0.0.0.0:8084"
    volumes:
      - ./:/usr/src/imageassistant/
      - static:/usr/src/imageassistant/imageassistant/config/static/
    expose:
      - 8084:8084
    networks:
      - imageassistant-network
  celery-imageassistant:
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    volumes:
      # change to your base directory
      - ./:/usr/src/imageassistant/
    command: >
      sh -c "celery -A config worker --loglevel=info --max-tasks-per-child=1 --concurrency=4"
    depends_on:
      - redis-imageassistant
    networks:
      - imageassistant-network
networks:
  imageassistant-network:
    driver: bridge

volumes:
  static:
  redis-data:


