# Generated by Django 4.2.14 on 2024-08-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
