# Generated by Django 4.2.14 on 2024-08-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='processed',
            field=models.BooleanField(default=True),
        ),
    ]
