# Generated by Django 4.2.14 on 2024-08-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_change_processed_to_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
