# Generated by Django 4.2.16 on 2024-10-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_add_alternate_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(choices=[('Greyscale', 'Greyscale'), ('Remove Background', 'Remove Background'), ('Resize', 'Resize'), ('Thumbnail', 'Thumbnail')], max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
