# Generated by Django 4.2.16 on 2024-10-28 18:48

from django.db import migrations


def populate_services(apps, schema_editor):
    Service = apps.get_model('images', 'Service')
    Service.objects.bulk_create([
        Service(name='Greyscale'),
        Service(name='Remove Background'),
        Service(name='Resize'),
        Service(name='Thumbnail')
    ])


def reverse_services(apps, schema_editor):
    Service = apps.get_model('images', 'Service')
    Service.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_service'),
    ]

    operations = [
        migrations.RunPython(populate_services, reverse_services),
    ]