# Generated by Django 4.2.16 on 2024-10-28 18:48

from django.db import migrations


def populate_services(apps, schema_editor):
    Service = apps.get_model('images', 'Service')
    Service.objects.bulk_create([
        Service(code=1, name='Greyscale'),
        Service(code=2, name='Remove Background'),
        Service(code=3, name='Resize'),
        Service(code=4, name='Thumbnail'),
        Service(code=7, name='Generate Image')
    ])


def reverse_services(apps, schema_editor):
    Service = apps.get_model('images', 'Service')
    Service.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_create_service_model'),
    ]

    operations = [
        migrations.RunPython(populate_services, reverse_services),
    ]