# Generated by Django 4.2.16 on 2024-12-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_populate_service_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Greyscale', 'Greyscale'), ('Remove Background', 'Remove Background'), ('Resize', 'Resize'), ('Thumbnail', 'Thumbnail'), ('Enhancement', 'Enhancement')], max_length=255),
        ),
    ]
