# Generated by Django 4.2.17 on 2024-12-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='poster_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='video_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Greyscale', 'Greyscale'), ('Remove Background', 'Remove Background'), ('Resize', 'Resize'), ('Thumbnail', 'Thumbnail'), ('Enhancement', 'Enhancement'), ('Cropping', 'Cropping')], max_length=255),
        ),
    ]
