# Generated by Django 4.2.17 on 2025-02-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_populate_fields_to_make_services_dynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='aspect_ratio',
            field=models.CharField(default='16:9', max_length=50),
        ),
    ]
