# Generated by Django 4.2.17 on 2025-02-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_added_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ai_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Greyscale', 'Greyscale'), ('Remove Background', 'Remove Background'), ('Resize', 'Resize'), ('Thumbnail', 'Thumbnail'), ('Enhancement', 'Enhancement'), ('Cropping', 'Cropping'), ('GenerateImage', 'GenerateImage')], max_length=255),
        ),
    ]
