# Generated by Django 4.2.17 on 2025-02-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_add_jsonfield_for_api_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='payment_made',
            field=models.BooleanField(default=False),
        ),
    ]
