# Generated by Django 4.2.17 on 2025-02-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_added_payment_made_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='payment_made',
        ),
        migrations.AddField(
            model_name='image',
            name='payment_made',
            field=models.BooleanField(default=False),
        ),
    ]
