# Generated by Django 4.2.17 on 2025-02-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_move_payment_made_to_image_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alternate_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
