# Generated by Django 4.2.17 on 2025-03-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_add_user_and_prompt_to_image_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='poster_path',
        ),
        migrations.RemoveField(
            model_name='service',
            name='video_path',
        ),
    ]
