# Generated by Django 4.2.20 on 2025-07-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0020_remove_video_and_poster_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='cost',
            new_name='tokens',
        ),
    ]
