# Generated by Django 4.2.20 on 2025-07-11 08:35

from django.db import migrations

def add_token_cost_to_services(apps, schema_editor):
    Service = apps.get_model('images', 'Service')
    # create a new Service for image outline
    Service.objects.get_or_create(
        code=8,
        name='Image Outline',
        description='Create an outline of the image',
    )
    # Add a default token cost to existing services
    for service in Service.objects.all():
        match service.code:
            case 1:  # Greyscale
                service.tokens = 1
            case 2:  # Remove Background
                service.tokens = 3
            case 3:  # Resize
                service.tokens = 1
            case 4:  # Thumbnail
                service.tokens = 1
            case 7:  # Generate Image
                service.tokens = 9
            case 8:  # Image Outline
                service.tokens = 2
        service.save()

class Migration(migrations.Migration):

    dependencies = [
        ('images', '0021_change_cost_to_tokens'),
    ]

    operations = [
    ]
    # also reverser the migration
    operations = [
        migrations.RunPython(add_token_cost_to_services, reverse_code=migrations.RunPython.noop),
    ]