- name: My first play
  hosts: webservers
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Check if the directory exists
     ansible.builtin.stat:
        path: /home/ubuntu/imageassistant
     register: git_dir_stat

   - name: Git pull if the repository exists
     become: yes
     become_user: root
     ansible.builtin.git:
       repo: https://github.com/squadran2003/imageassistant
       version: main
       dest: /home/ubuntu/imageassistant
       update: yes
     when: git_dir_stat.stat.exists

   - name: Git clone if the repository does not exist
     become: yes
     become_user: root
     ansible.builtin.git:
       repo: https://github.com/squadran2003/imageassistant
       dest: /home/ubuntu/imageassistant
       version: main
     when: not git_dir_stat.stat.exists

   - name: Bring docker containers down
     become: yes
     become_user: root     
     ansible.builtin.shell:  
       chdir: /home/ubuntu/imageassistant
       cmd: docker-compose -f docker-compose-prod.yaml down
     register: command_result      

   - name: Bring docker containers up
     become: yes
     become_user: root
     ansible.builtin.shell:
       chdir: /home/ubuntu/imageassistant
       cmd: docker-compose -f docker-compose-prod.yaml up --build -d
     register: command_result       

   - name: Display command output
     ansible.builtin.debug:
       var: command_result.stdout
